In [1]:
import pandas as pd

In [2]:
df=pd.read_csv("Salaries.csv")

In [3]:
df.head()

rank discipline  phd  service   sex  salary
0  Prof          B   56       49  Male  186960
1  Prof          A   12        6  Male   93000
2  Prof          A   23       20  Male  110515
3  Prof          A   40       31  Male  131205
4  Prof          B   20       18  Male  104800

In [4]:
df.head(10)

rank discipline  phd  service   sex  salary
0       Prof          B   56       49  Male  186960
1       Prof          A   12        6  Male   93000
2       Prof          A   23       20  Male  110515
3       Prof          A   40       31  Male  131205
4       Prof          B   20       18  Male  104800
5       Prof          A   20       20  Male  122400
6  AssocProf          A   20       17  Male   81285
7       Prof          A   18       18  Male  126300
8       Prof          A   29       19  Male   94350
9       Prof          A   51       51  Male   57800

In [5]:
df.shape

(78, 6)

df.columns()

In [6]:
df.columns

Index(['rank', 'discipline', 'phd', 'service', 'sex', 'salary'], dtype='object')

df.dtypes

In [7]:
df.size

468

In [8]:
df.describe()

phd    service         salary
count  78.000000  78.000000      78.000000
mean   19.705128  15.051282  108023.782051
std    12.498425  12.139768   28293.661022
min     1.000000   0.000000   57800.000000
25%    10.250000   5.250000   88612.500000
50%    18.500000  14.500000  104671.000000
75%    27.750000  20.750000  126774.750000
max    56.000000  51.000000  186960.000000

In [9]:
df.std()

C:\Users\anike\AppData\Local\Temp\ipykernel_27760\3390915376.py:1: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  df.std()


phd           12.498425
service       12.139768
salary     28293.661022
dtype: float64

In [10]:
df.head(50).mean()

C:\Users\anike\AppData\Local\Temp\ipykernel_27760\1648960742.py:1: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  df.head(50).mean()


phd            21.52
service        17.60
salary     113789.14
dtype: float64

In [11]:
df['phd'].describe()

count    78.000000
mean     19.705128
std      12.498425
min       1.000000
25%      10.250000
50%      18.500000
75%      27.750000
max      56.000000
Name: phd, dtype: float64

In [12]:
df['phd'].mode()

0    4
Name: phd, dtype: int64

In [13]:
df['phd'].median()

18.5

In [14]:
df['phd'].count()

78

In [15]:
df['phd'].mean()

19.705128205128204

In [16]:
df['phd'].var()

156.21062271062277

In [17]:
df.groupby('discipline')[['service']].mean()

service
discipline           
A           15.722222
B           14.476190

In [18]:
df[df['salary']>120000]

rank discipline  phd  service     sex  salary
0   Prof          B   56       49    Male  186960
3   Prof          A   40       31    Male  131205
5   Prof          A   20       20    Male  122400
7   Prof          A   18       18    Male  126300
10  Prof          B   39       33    Male  128250
11  Prof          B   23       23    Male  134778
13  Prof          B   35       33    Male  162200
14  Prof          B   25       19    Male  153750
15  Prof          B   17        3    Male  150480
19  Prof          A   29       27    Male  150500
26  Prof          A   38       19    Male  148750
27  Prof          A   45       43    Male  155865
29  Prof          B   21       20    Male  123683
31  Prof          B   22       21    Male  155750
35  Prof          B   28       23    Male  126933
36  Prof          B   45       45    Male  146856
39  Prof          B   18       18  Female  129000
40  Prof          A   39       36  Female  137000
44  Prof          B   23       19  Female  151768
45  Prof          B   25       25  Female  140096
49  Prof          B   17       18  Female  122960
51  Prof          B   20       14  Female  127512
58  Prof          B   36       26  Female  144651
72  Prof          B   24       15  Female  161101
75  Prof          B   17       17  Female  124312

In [19]:
  df[df['sex']=='Female']

rank discipline  phd  service     sex  salary
39       Prof          B   18       18  Female  129000
40       Prof          A   39       36  Female  137000
41  AssocProf          A   13        8  Female   74830
42   AsstProf          B    4        2  Female   80225
43   AsstProf          B    5        0  Female   77000
44       Prof          B   23       19  Female  151768
45       Prof          B   25       25  Female  140096
46   AsstProf          B   11        3  Female   74692
47  AssocProf          B   11       11  Female  103613
48       Prof          B   17       17  Female  111512
49       Prof          B   17       18  Female  122960
50   AsstProf          B   10        5  Female   97032
51       Prof          B   20       14  Female  127512
52       Prof          A   12        0  Female  105000
53   AsstProf          A    5        3  Female   73500
54  AssocProf          A   25       22  Female   62884
55   AsstProf          A    2        0  Female   72500
56  AssocProf          A   10        8  Female   77500
57   AsstProf          A    3        1  Female   72500
58       Prof          B   36       26  Female  144651
59  AssocProf          B   12       10  Female  103994
60   AsstProf          B    3        3  Female   92000
61  AssocProf          B   13       10  Female  103750
62  AssocProf          B   14        7  Female  109650
63       Prof          A   29       27  Female   91000
64  AssocProf          A   26       24  Female   73300
65       Prof          A   36       19  Female  117555
66   AsstProf          A    7        6  Female   63100
67       Prof          A   17       11  Female   90450
68   AsstProf          A    4        2  Female   77500
69       Prof          A   28        7  Female  116450
70   AsstProf          A    8        3  Female   78500
71  AssocProf          B   12        9  Female   71065
72       Prof          B   24       15  Female  161101
73       Prof          B   18       10  Female  105450
74  AssocProf          B   19        6  Female  104542
75       Prof          B   17       17  Female  124312
76       Prof          A   28       14  Female  109954
77       Prof          A   23       15  Female  109646

In [20]:
df[(df['rank']=='Prof') & (df['rank']=='Prof')]

rank discipline  phd  service     sex  salary
0   Prof          B   56       49    Male  186960
1   Prof          A   12        6    Male   93000
2   Prof          A   23       20    Male  110515
3   Prof          A   40       31    Male  131205
4   Prof          B   20       18    Male  104800
5   Prof          A   20       20    Male  122400
7   Prof          A   18       18    Male  126300
8   Prof          A   29       19    Male   94350
9   Prof          A   51       51    Male   57800
10  Prof          B   39       33    Male  128250
11  Prof          B   23       23    Male  134778
13  Prof          B   35       33    Male  162200
14  Prof          B   25       19    Male  153750
15  Prof          B   17        3    Male  150480
18  Prof          A   19        7    Male  107300
19  Prof          A   29       27    Male  150500
21  Prof          A   33       30    Male  103106
24  Prof          A   30       23    Male   91100
25  Prof          B   35       31    Male   99418
26  Prof          A   38       19    Male  148750
27  Prof          A   45       43    Male  155865
29  Prof          B   21       20    Male  123683
31  Prof          B   22       21    Male  155750
32  Prof          A   27       19    Male  103275
33  Prof          B   18       18    Male  120000
35  Prof          B   28       23    Male  126933
36  Prof          B   45       45    Male  146856
37  Prof          A   20        8    Male  102000
39  Prof          B   18       18  Female  129000
40  Prof          A   39       36  Female  137000
44  Prof          B   23       19  Female  151768
45  Prof          B   25       25  Female  140096
48  Prof          B   17       17  Female  111512
49  Prof          B   17       18  Female  122960
51  Prof          B   20       14  Female  127512
52  Prof          A   12        0  Female  105000
58  Prof          B   36       26  Female  144651
63  Prof          A   29       27  Female   91000
65  Prof          A   36       19  Female  117555
67  Prof          A   17       11  Female   90450
69  Prof          A   28        7  Female  116450
72  Prof          B   24       15  Female  161101
73  Prof          B   18       10  Female  105450
75  Prof          B   17       17  Female  124312
76  Prof          A   28       14  Female  109954
77  Prof          A   23       15  Female  109646

In [21]:
df.iloc[0:10]

rank discipline  phd  service   sex  salary
0       Prof          B   56       49  Male  186960
1       Prof          A   12        6  Male   93000
2       Prof          A   23       20  Male  110515
3       Prof          A   40       31  Male  131205
4       Prof          B   20       18  Male  104800
5       Prof          A   20       20  Male  122400
6  AssocProf          A   20       17  Male   81285
7       Prof          A   18       18  Male  126300
8       Prof          A   29       19  Male   94350
9       Prof          A   51       51  Male   57800

EDA


In [22]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [23]:
data=pd.read_csv(r"data_clean.csv")

In [24]:
data.head()

Unnamed: 0  Ozone  Solar.R  Wind Temp C Month  Day  Year  Temp Weather
0           1   41.0    190.0   7.4     67     5    1  2010    67       S
1           2   36.0    118.0   8.0     72     5    2  2010    72       C
2           3   12.0    149.0  12.6     74     5    3  2010    74      PS
3           4   18.0    313.0  11.5     62     5    4  2010    62       S
4           5    NaN      NaN  14.3     56     5    5  2010    56       S

In [25]:
data.shape

(158, 10)

In [26]:
data.dtypes

Unnamed: 0      int64
Ozone         float64
Solar.R       float64
Wind          float64
Temp C         object
Month          object
Day             int64
Year            int64
Temp            int64
Weather        object
dtype: object

In [27]:
data.describe()

Unnamed: 0       Ozone     Solar.R        Wind         Day    Year  \
count  158.000000  120.000000  151.000000  158.000000  158.000000   158.0   
mean    79.500000   41.583333  185.403974    9.957595   16.006329  2010.0   
std     45.754781   32.620709   88.723103    3.511261    8.997166     0.0   
min      1.000000    1.000000    7.000000    1.700000    1.000000  2010.0   
25%     40.250000   18.000000  119.000000    7.400000    8.000000  2010.0   
50%     79.500000   30.500000  197.000000    9.700000   16.000000  2010.0   
75%    118.750000   61.500000  257.000000   11.875000   24.000000  2010.0   
max    158.000000  168.000000  334.000000   20.700000   31.000000  2010.0   

             Temp  
count  158.000000  
mean    77.727848  
std      9.377877  
min     56.000000  
25%     72.000000  
50%     78.500000  
75%     84.000000  
max     97.000000

In [28]:
data['Ozone'].isnull().sum()

38

In [29]:
data['Month']=pd.to_numeric(data['Month'],errors='coerce')

In [30]:
data['Month']

0      5.0
1      5.0
2      5.0
3      5.0
4      5.0
      ... 
153    5.0
154    9.0
155    9.0
156    9.0
157    9.0
Name: Month, Length: 158, dtype: float64

In [31]:
data['Temp']=pd.to_numeric(data['Temp'],errors='coerce')
data['Weather']=data['Weather'].astype('category')

In [32]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 158 entries, 0 to 157
Data columns (total 10 columns):
 #   Column      Non-Null Count  Dtype   
---  ------      --------------  -----   
 0   Unnamed: 0  158 non-null    int64   
 1   Ozone       120 non-null    float64 
 2   Solar.R     151 non-null    float64 
 3   Wind        158 non-null    float64 
 4   Temp C      158 non-null    object  
 5   Month       157 non-null    float64 
 6   Day         158 non-null    int64   
 7   Year        158 non-null    int64   
 8   Temp        158 non-null    int64   
 9   Weather     155 non-null    category
dtypes: category(1), float64(4), int64(4), object(1)
memory usage: 11.5+ KB


In [33]:
data_cleaned=data.drop('Temp C',axis=1)

In [34]:
data_cleaned.shape

(158, 9)

In [35]:
data_cleaned=data_cleaned.rename({"Solar.R":"Solar"},axis=1)

In [36]:
data_cleaned

Unnamed: 0  Ozone  Solar  Wind  Month  Day  Year  Temp Weather
0             1   41.0  190.0   7.4    5.0    1  2010    67       S
1             2   36.0  118.0   8.0    5.0    2  2010    72       C
2             3   12.0  149.0  12.6    5.0    3  2010    74      PS
3             4   18.0  313.0  11.5    5.0    4  2010    62       S
4             5    NaN    NaN  14.3    5.0    5  2010    56       S
..          ...    ...    ...   ...    ...  ...   ...   ...     ...
153         154   41.0  190.0   7.4    5.0    1  2010    67       C
154         155   30.0  193.0   6.9    9.0   26  2010    70      PS
155         156    NaN  145.0  13.2    9.0   27  2010    77       S
156         157   14.0  191.0  14.3    9.0   28  2010    75       S
157         158   18.0  131.0   8.0    9.0   29  2010    76       C

[158 rows x 9 columns]

In [37]:
df=pd.read_csv('basic_salary.csv')

In [38]:
df.head()

First_Name Last_Name Grade Location     ba       ms
0       Alan     Brown   GR1    DELHI  17990  16070.0
1     Agatha  Williams   GR2   MUMBAI  12390   6630.0
2     Rajesh     Kolte   GR1   MUMBAI  19250  14960.0
3      Ameet    Mishra   GR2    DELHI  14780   9300.0
4       Neha       Rao   GR1   MUMBAI  19235  15200.0

In [39]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   First_Name  12 non-null     object 
 1   Last_Name   12 non-null     object 
 2   Grade       12 non-null     object 
 3   Location    12 non-null     object 
 4   ba          12 non-null     int64  
 5   ms          11 non-null     float64
dtypes: float64(1), int64(1), object(4)
memory usage: 704.0+ bytes


In [40]:
df['Location']=df['Location'].astype('category')

In [41]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype   
---  ------      --------------  -----   
 0   First_Name  12 non-null     object  
 1   Last_Name   12 non-null     object  
 2   Grade       12 non-null     object  
 3   Location    12 non-null     category
 4   ba          12 non-null     int64   
 5   ms          11 non-null     float64 
dtypes: category(1), float64(1), int64(1), object(3)
memory usage: 744.0+ bytes


In [42]:
df['Location']

0      DELHI
1     MUMBAI
2     MUMBAI
3      DELHI
4     MUMBAI
5     MUMBAI
6     MUMBAI
7     MUMBAI
8      DELHI
9      DELHI
10     DELHI
11    MUMBAI
Name: Location, dtype: category
Categories (2, object): ['DELHI', 'MUMBAI']

In [43]:
df['Location'].cat.categories

Index(['DELHI', 'MUMBAI'], dtype='object')

In [44]:
df.describe()

ba            ms
count     12.000000     11.000000
mean   16154.583333  11004.545455
std     3739.378569   3711.189469
min    11960.000000   6630.000000
25%    13472.500000   7360.000000
50%    14270.000000  10760.000000
75%    19238.750000  14225.000000
max    23280.000000  16070.000000

In [45]:
df['ba']

0     17990
1     12390
2     19250
3     14780
4     19235
5     13390
6     23280
7     13500
8     20660
9     13760
10    13660
11    11960
Name: ba, dtype: int64

In [46]:
df.ba

0     17990
1     12390
2     19250
3     14780
4     19235
5     13390
6     23280
7     13500
8     20660
9     13760
10    13660
11    11960
Name: ba, dtype: int64

In [47]:
df[df['Location']=='MUMBAI']

First_Name Last_Name Grade Location     ba       ms
1      Agatha  Williams   GR2   MUMBAI  12390   6630.0
2      Rajesh     Kolte   GR1   MUMBAI  19250  14960.0
4        Neha       Rao   GR1   MUMBAI  19235  15200.0
5       Sagar    Chavan   GR2   MUMBAI  13390   6700.0
6       Aaron     Jones   GR1   MUMBAI  23280  13490.0
7        John     Patil   GR2   MUMBAI  13500  10760.0
11       Anup      Save   GR2   MUMBAI  11960   7880.0

In [48]:
df['ba'].agg(['mean','min','max'])

mean    16154.583333
min     11960.000000
max     23280.000000
Name: ba, dtype: float64

In [49]:
df['Grade'].mode()

0    GR2
Name: Grade, dtype: object

In [50]:
data_cleaned.values

array([[1, 41.0, 190.0, ..., 2010, 67, 'S'],
       [2, 36.0, 118.0, ..., 2010, 72, 'C'],
       [3, 12.0, 149.0, ..., 2010, 74, 'PS'],
       ...,
       [156, nan, 145.0, ..., 2010, 77, 'S'],
       [157, 14.0, 191.0, ..., 2010, 75, 'S'],
       [158, 18.0, 131.0, ..., 2010, 76, 'C']], dtype=object)

In [51]:
data_cleaned4=pd.get_dummies(data_cleaned,columns=['Weather'])
data_cleaned4

Unnamed: 0  Ozone  Solar  Wind  Month  Day  Year  Temp  Weather_C  \
0             1   41.0  190.0   7.4    5.0    1  2010    67          0   
1             2   36.0  118.0   8.0    5.0    2  2010    72          1   
2             3   12.0  149.0  12.6    5.0    3  2010    74          0   
3             4   18.0  313.0  11.5    5.0    4  2010    62          0   
4             5    NaN    NaN  14.3    5.0    5  2010    56          0   
..          ...    ...    ...   ...    ...  ...   ...   ...        ...   
153         154   41.0  190.0   7.4    5.0    1  2010    67          1   
154         155   30.0  193.0   6.9    9.0   26  2010    70          0   
155         156    NaN  145.0  13.2    9.0   27  2010    77          0   
156         157   14.0  191.0  14.3    9.0   28  2010    75          0   
157         158   18.0  131.0   8.0    9.0   29  2010    76          1   

     Weather_PS  Weather_S  
0             0          1  
1             0          0  
2             1          0  
3             0          1  
4             0          1  
..          ...        ...  
153           0          0  
154           1          0  
155           0          1  
156           0          1  
157           0          0  

[158 rows x 11 columns]

In [52]:
data_cleaned4=data_cleaned4.dropna()

In [53]:
from numpy import set_printoptions
from sklearn.preprocessing import MinMaxScaler

In [54]:
array = data_cleaned4.values

scaler = MinMaxScaler(feature_range=(0,1))
rescaledX = scaler.fit_transform(array)

#transformed data
set_printoptions(precision=2)
print(rescaledX[0:5,:])

[[0.   0.24 0.56 0.28 0.   0.   0.   0.25 0.   0.   1.  ]
 [0.01 0.21 0.34 0.31 0.   0.03 0.   0.38 1.   0.   0.  ]
 [0.01 0.07 0.43 0.56 0.   0.07 0.   0.43 0.   1.   0.  ]
 [0.02 0.1  0.94 0.5  0.   0.1  0.   0.12 0.   0.   1.  ]
 [0.04 0.13 0.89 0.34 0.   0.2  0.   0.2  0.   1.   0.  ]]


In [55]:
from sklearn.preprocessing import StandardScaler

In [56]:
array = data_cleaned4.values
scaler = StandardScaler()
scaler.fit(array)
rescaledX = scaler.transform(array)

# summarize transformed data
set_printoptions(precision=2)
print(rescaledX[0:5,:])

[[-1.84 -0.02  0.05 -0.71 -1.53 -1.7   0.   -1.15 -0.64 -0.68  1.28]
 [-1.82 -0.17 -0.75 -0.54 -1.53 -1.59  0.   -0.62  1.57 -0.68 -0.78]
 [-1.8  -0.9  -0.41  0.77 -1.53 -1.48  0.   -0.4  -0.64  1.47 -0.78]
 [-1.78 -0.72  1.43  0.45 -1.53 -1.36  0.   -1.69 -0.64 -0.68  1.28]
 [-1.71 -0.57  1.27 -0.37 -1.53 -1.02  0.   -1.37 -0.64  1.47 -0.78]]


In [57]:
from scipy import stats
stats.norm.cdf(70,60,10)

0.8413447460685429

In [58]:
1-stats.norm.cdf(680,711,29)

0.8574573961611839

In [59]:
x=stats.norm.cdf(740,711,29)

In [60]:
y=1-stats.norm.cdf(697,711,29)

In [61]:
x-y

0.155978313495584

In [62]:
df=pd.read_csv("beml_df.csv")

In [63]:
df.head(5)

Date      Date.1    Close      gain
0  2010-01-05  2010-01-05  1134.60 -0.000881
1  2010-01-06  2010-01-06  1139.60  0.004407
2  2010-01-07  2010-01-07  1144.15  0.003993
3  2010-01-08  2010-01-08  1144.05 -0.000087
4  2010-01-11  2010-01-11  1137.00 -0.006162

In [64]:
data=pd.read_csv("Glaxo.csv")

In [65]:
data.head(5)

date     Open     High      Low    Last    Close  \
0  04-01-2010  1613.00  1629.10  1602.00  1629.0  1625.65   
1  05-01-2010  1639.95  1639.95  1611.05  1620.0  1616.80   
2  06-01-2010  1618.00  1644.00  1617.00  1639.0  1638.50   
3  07-01-2010  1645.00  1654.00  1636.00  1648.0  1648.70   
4  08-01-2010  1650.00  1650.00  1626.55  1640.0  1639.80   

   Total Trade Quantity  Turnover (Lacs)  
0                  9365           151.74  
1                 38148           622.58  
2                 36519           595.09  
3                 12809           211.00  
4                 28035           459.11

In [66]:
df=df[['Date','Close']]

In [67]:
df

Date    Close
0     2010-01-05  1134.60
1     2010-01-06  1139.60
2     2010-01-07  1144.15
3     2010-01-08  1144.05
4     2010-01-11  1137.00
...          ...      ...
1733  2016-12-26   950.25
1734  2016-12-27   975.70
1735  2016-12-28   974.40
1736  2016-12-29   986.05
1737  2016-12-30  1000.60

[1738 rows x 2 columns]

In [68]:
data=data[['Date','Close']]
data.head()

KeyError: "['Date'] not in index"

In [ ]:
data = data.set_index(pd.DatetimeIndex(data['Date'])).drop('Date',axis=1)
beml_df = beml_df.set_index(pd.DatetimeIndex(beml_df['Date'])).drop('Date',axis=1)

In [ ]:
data=[34,36,36,38,38,39,39,40,40,41,41,41,41,42,42,45,49,56]

In [ ]:
df=pd.DataFrame(data,columns=['VD'])

In [ ]:
df

In [ ]:
df['VD'].std()

In [ ]:
data=pd.read_csv('Q7.csv')

In [ ]:
data


In [ ]:
data['Weigh'].ran(14,25)

In [ ]:
range1=max(data['Weigh'])-min(data['Weigh'])
range1

In [76]:
data=pd.read_csv('Q9_a.csv')
data

Index  speed  dist
0       1      4     2
1       2      4    10
2       3      7     4
3       4      7    22
4       5      8    16
5       6      9    10
6       7     10    18
7       8     10    26
8       9     10    34
9      10     11    17
10     11     11    28
11     12     12    14
12     13     12    20
13     14     12    24
14     15     12    28
15     16     13    26
16     17     13    34
17     18     13    34
18     19     13    46
19     20     14    26
20     21     14    36
21     22     14    60
22     23     14    80
23     24     15    20
24     25     15    26
25     26     15    54
26     27     16    32
27     28     16    40
28     29     17    32
29     30     17    40
30     31     17    50
31     32     18    42
32     33     18    56
33     34     18    76
34     35     18    84
35     36     19    36
36     37     19    46
37     38     19    68
38     39     20    32
39     40     20    48
40     41     20    52
41     42     20    56
42     43     20    64
43     44     22    66
44     45     23    54
45     46     24    70
46     47     24    92
47     48     24    93
48     49     24   120
49     50     25    85

In [ ]:
data
import scipy

In [ ]:
scipy.stats.

In [77]:
scipy.stats.kurtosis(data['speed'],axis=0,bias=True)

-0.5771474239437371

In [73]:
data=pd.read_csv('Q9_b.csv')
data


Unnamed: 0          SP         WT
0            1  104.185353  28.762059
1            2  105.461264  30.466833
2            3  105.461264  30.193597
3            4  113.461264  30.632114
4            5  104.461264  29.889149
..         ...         ...        ...
76          77  169.598513  16.132947
77          78  150.576579  37.923113
78          79  151.598513  15.769625
79          80  167.944460  39.423099
80          81  139.840817  34.948615

[81 rows x 3 columns]

In [72]:
import scipy

In [71]:
scipy.stats.skew(data['SP'],axis=0,bias=True)

1.5814536794423764

In [75]:
scipy.stats.skew(data['WT'],axis=0,bias=True)

-0.6033099322115126

In [ ]:
from scipy.stats import chi2_contingency

In [ ]:
data=[[14,4],[0,10]]

In [ ]:
data

In [ ]:
stat,p,dof,expected=chi2_contingency(data)

In [ ]:
stat

In [ ]:
p

In [ ]:
dof

In [ ]:
expected

In [ ]:
data1=[[207,282,241],[234,242,232]]


In [ ]:
stat,p,dof,expected=chi2_contingency(data1)

In [ ]:
p

In [ ]:
expected

In [ ]:
dof

In [ ]:
stat

In [ ]:
alpha=0.05
print("p value is"+str(p))
if p<=alpha:
    print('dependent')
else:
    print('independent')